[package]
name = "findr"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
postcard = { version = "1.1.3", features = ["use-std", "use-crc"] }
rayon = "1.11.0"
serde = { version = "1", features = ["derive", "std"] }
